{% set name = "cellfinder" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cellfinder-{{ version }}.tar.gz
  sha256: c59421bb17dae6805222650b2b4ebbe4edaa3fb125455c8c7e453b919c21870f

build:
  entry_points:
    - cellfinder_download = cellfinder.core.download.cli:main
    - cellfinder_train = cellfinder.core.train.train_yml:cli
    - cellfinder = cellfinder.cli_migration_warning:cli_catch
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.10
    - brainglobe-utils >=0.5.0
    - brainglobe-napari-io >=0.3.4
    - dask-core
    - fancylog >=0.0.7
    - natsort
    - numba
    - numpy <2
    - scikit-image
    - scikit-learn
    - keras >=3.0.0
    - pytorch >=2.1.0
    - tifffile
    - tqdm

test:
  imports:
    - cellfinder
  commands:
    - pip check
    - cellfinder_download --help
    - cellfinder_train --help
    - cellfinder --help
  requires:
    - pip

about:
  summary: Automated 3D cell detection in large microscopy images
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alessandrofelder
    - adamltyson
