{% set name = "dramatiq-abort" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dramatiq_abort-{{ version }}.tar.gz
  sha256: 795ee9a37d884d70e63b758031017cd1f7c33f40db5f4901aaa95fcb659c13c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - dramatiq

test:
  imports:
    - dramatiq_abort
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/flared/dramatiq-abort
  summary: Dramatiq middleware to abort tasks.
  license: LGPL-3.0-only
  license_file: LICENSE
  doc_url: https://flared.github.io/dramatiq-abort/
  dev_url: https://github.com/Flared/dramatiq-abort

extra:
  recipe-maintainers:
    - davner
